import Link from "next/link";
import { InstallationForm } from "@/components/installation/InstallationForm";
import { Section } from "@/components/ui/Section";
import { BUSINESS } from "@/lib/constants";
import { dispatchServiceHref } from "@/lib/scheduling";

export function InstallationLanding() {
  const dispatch = dispatchServiceHref("installation");
  return <>
    <section className="bg-neutral-950 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-8 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:items-start lg:px-8 lg:py-12">
      <div className="pt-3"><p className="font-bold uppercase tracking-wider text-red-400">Free In-Home Installation Estimate</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight sm:text-5xl">AC Replacement &amp; Installation in Los Angeles and Orange County</h1><p className="mt-4 max-w-2xl text-lg leading-relaxed text-white/80">Get a free in-home estimate for a central AC, heat pump or mini-split system. Financing options available.</p>
        <ul className="mt-6 grid gap-2 text-white/85 sm:grid-cols-2"><li>✓ Professional system sizing</li><li>✓ Energy-efficient options</li><li>✓ Warranty guidance</li><li>✓ Permits when required</li></ul>
        <div className="mt-7 flex flex-wrap gap-3"><a href={`tel:${BUSINESS.phoneE164}`} data-cta="installation-phone" data-cta-type="phone" data-cta-location="installation-hero" className="rounded-xl border border-white/30 px-5 py-3 font-extrabold">Call {BUSINESS.phoneDisplay}</a><a href={dispatch} target="_blank" rel="noopener noreferrer" data-cta="installation-dispatch" data-cta-type="booking" data-cta-location="installation-hero" className="rounded-xl bg-white px-5 py-3 font-extrabold text-black">Schedule an In-Home Visit</a></div>
      </div><div id="estimate-form" className="rounded-2xl bg-white p-5 text-black shadow-2xl sm:p-7"><h2 className="text-2xl font-extrabold">Get My Free Estimate</h2><p className="mb-5 mt-1 text-sm text-black/65">Tell us about your project. You can request an estimate without scheduling first.</p><InstallationForm /></div>
    </div></section>
    <Section><div className="grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-extrabold">Installation built around your home</h2><p className="mt-4 leading-relaxed text-black/70">We evaluate square footage, insulation, sun exposure, electrical needs and ductwork before recommending equipment. Correct sizing improves comfort, efficiency and equipment life.</p><p className="mt-4 leading-relaxed text-black/70">Your proposal explains equipment choices, the installation process, warranty coverage, financing and any permits that apply.</p></div><div className="rounded-2xl bg-brand-gray p-6"><h2 className="text-2xl font-extrabold">Systems we install</h2><ul className="mt-4 space-y-3 text-black/75"><li><strong>Central AC:</strong> whole-home cooling with existing or updated ductwork.</li><li><strong>Heat pumps:</strong> efficient cooling and heating in one system.</li><li><strong>Mini-splits:</strong> quiet, zoned comfort without traditional ducts.</li></ul></div></div></Section>
    <Section className="bg-brand-gray"><div className="max-w-4xl"><h2 className="text-3xl font-extrabold">Do You Need a Repair or a Full System Replacement?</h2><p className="mt-4 leading-relaxed text-black/70">Choose repair when a generally reliable system has a specific fault. Consider replacement when equipment is aging, needs frequent repairs, uses outdated technology or can no longer cool the home efficiently.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/residential/residential-ac-repair/" className="rounded-xl border border-black/20 bg-white px-5 py-3 font-bold">I need AC repair</Link><Link href="#estimate-form" className="rounded-xl bg-brand-red px-5 py-3 font-bold text-white">Request a replacement estimate</Link></div></div></Section>
    <Section><h2 className="text-3xl font-extrabold">What to expect</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["1", "In-home assessment", "We review your home, comfort goals and existing system."],["2", "Clear options", "Compare right-sized systems, efficiency and financing."],["3", "Professional installation", "Removal, installation and permits when required."],["4", "Testing & warranty", "We verify operation and explain care and coverage."]].map(([n,t,d]) => <div key={n} className="rounded-2xl border border-black/10 p-5"><span className="font-extrabold text-brand-red">Step {n}</span><h3 className="mt-1 font-extrabold">{t}</h3><p className="mt-2 text-sm leading-relaxed text-black/65">{d}</p></div>)}</div></Section>
  </>;
}
