import Link from "next/link";
import { InstallationForm } from "@/components/installation/InstallationForm";
import { HousecallProNativeLeadForm } from "@/components/installation/HousecallProNativeLeadForm";
import { Section } from "@/components/ui/Section";
import { INSTALLATION_CONSULTATION_CTA, INSTALLATION_CONSULTATION_HEADING } from "@/lib/consultation";

export function InstallationLanding() {
  const nativeLeadFormUrl = process.env.HOUSECALL_PRO_MODE === "native" ? process.env.NEXT_PUBLIC_HOUSECALL_PRO_LEAD_FORM_URL : undefined;
  return <>
    <section className="bg-neutral-950 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-8 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:items-start lg:px-8 lg:py-12">
      <div className="pt-3"><p className="font-bold uppercase tracking-wider text-red-400">{INSTALLATION_CONSULTATION_HEADING}</p><h1 className="mt-3 text-balance text-4xl font-extrabold tracking-tight sm:text-5xl">Free HVAC Installation Consultation for AC Replacement &amp; New Systems</h1><p className="mt-4 max-w-2xl text-lg leading-relaxed text-white/80">Get a free estimate for central AC, heat pump or mini-split installation and replacement. Financing options available.</p>
        <ul className="mt-6 grid gap-2 text-white/85 sm:grid-cols-2"><li>✓ Professional system sizing</li><li>✓ Energy-efficient options</li><li>✓ Warranty guidance</li><li>✓ Free estimates for installations &amp; replacements</li></ul>
        <div className="mt-7 flex flex-wrap gap-3"><a href="#free-hvac-quote" data-quote-cta="installation-hero-primary" data-cta="installation-consultation" data-cta-type="form" data-cta-location="installation-hero" className="rounded-xl bg-white px-5 py-3 font-extrabold text-black focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">{INSTALLATION_CONSULTATION_CTA}</a><a href="#free-hvac-quote" data-quote-cta="installation-hero-secondary" data-cta="installation-project-guide" data-cta-type="form" data-cta-location="installation-hero" className="rounded-xl border border-white/30 px-5 py-3 font-extrabold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">Help Me Choose a System</a></div>
      </div><div id="free-hvac-quote" className="scroll-mt-24 rounded-2xl bg-white p-5 text-black shadow-2xl sm:p-7"><h2 className="text-balance text-2xl font-extrabold">{INSTALLATION_CONSULTATION_HEADING}</h2><p className="mb-5 mt-1 text-sm text-black/65">Answer a few quick questions for a free installation or replacement estimate. Your request creates a lead for personal follow-up—you do not need to schedule first.</p>{nativeLeadFormUrl ? <HousecallProNativeLeadForm url={nativeLeadFormUrl} /> : <InstallationForm />}</div>
    </div></section>
    <Section><div className="grid gap-8 lg:grid-cols-2"><div><h2 className="text-balance text-3xl font-extrabold">Installation built around your home</h2><p className="mt-4 leading-relaxed text-black/70">We evaluate square footage, insulation, sun exposure, electrical needs and ductwork before recommending equipment. Correct sizing improves comfort, efficiency and equipment life.</p><p className="mt-4 leading-relaxed text-black/70">Your free consultation and estimate explain equipment choices, the installation process, warranty coverage, financing and any permits that apply.</p></div><div className="rounded-2xl bg-brand-gray p-6"><h2 className="text-2xl font-extrabold">Systems we install</h2><ul className="mt-4 space-y-3 text-black/75"><li><strong>Central AC:</strong> whole-home cooling with existing or updated ductwork.</li><li><strong>Heat pumps:</strong> efficient cooling and heating in one system.</li><li><strong>Mini-splits:</strong> quiet, zoned comfort without traditional ducts.</li></ul></div></div></Section>
    <Section className="bg-brand-gray"><div className="max-w-4xl"><h2 className="text-balance text-3xl font-extrabold">Do You Need a Repair or a Full System Replacement?</h2><p className="mt-4 leading-relaxed text-black/70">Choose repair when a generally reliable system has a specific fault. Consider replacement when equipment is aging, needs frequent repairs, uses outdated technology or can no longer cool the home efficiently.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="#free-hvac-quote" data-quote-cta="repair-or-replace-guide" className="rounded-xl border border-black/20 bg-white px-5 py-3 font-bold">Help me decide</Link><Link href="#free-hvac-quote" data-quote-cta="replacement-section" className="rounded-xl bg-brand-red px-5 py-3 font-bold text-white">{INSTALLATION_CONSULTATION_CTA}</Link></div></div></Section>
    <Section><h2 className="text-3xl font-extrabold">What to expect</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["1", "Tell us what you need", "Use the consultation guide—no appointment required."], ["2", "Personal follow-up", "Our team reviews your needs and contacts you."], ["3", "In-home assessment", "We size the right system and explain your options."], ["4", "Free estimate", "Review equipment, financing, installation and warranty."]].map(([n, t, d]) => <div key={n} className="rounded-2xl border border-black/10 p-5"><span className="font-extrabold text-brand-red">Step {n}</span><h3 className="mt-1 font-extrabold">{t}</h3><p className="mt-2 text-sm leading-relaxed text-black/65">{d}</p></div>)}</div><a href="#free-hvac-quote" data-quote-cta="what-to-expect" className="mt-7 inline-flex rounded-xl bg-brand-red px-5 py-3 font-extrabold text-white">{INSTALLATION_CONSULTATION_CTA}</a></Section>
  </>;
}
