"use client";
import { useState } from "react";
import { pushConversionEvent } from "@/lib/conversions";
import { PUBLIC_SCHEDULE_SERVICES, SERVICE_LABELS, isServiceType, type ServiceType } from "@/lib/service-types";
import { customerFlowHref } from "@/lib/scheduling";
export function ScheduleService({ locale, initialService, coupon }: { locale: "en" | "es"; initialService?: string; coupon?: string }) {
  const [selected, setSelected] = useState<ServiceType>(isServiceType(initialService) ? initialService : "other");
  const copy = locale === "es" ? { title: "Agende una consulta HVAC gratuita", intro: "Todos los servicios HVAC comienzan con una consulta gratuita. Los estimados gratuitos aplican a instalación y reemplazo después de una evaluación en sitio.", button: "Continuar", note: "Seleccione el servicio que necesita para dirigir su consulta correctamente." } : { title: "Book a Free HVAC Consultation", intro: "Every HVAC service begins with a free consultation. Free estimates apply to installation and replacement after an onsite assessment.", button: "Continue", note: "Choose the service you need so we can direct your consultation correctly." };
  function continueToCustomerFlow() { const destination = customerFlowHref(selected, locale, coupon); const event = selected === "installation" ? "installation_consultation_click" : selected === "maintenance" || selected === "commercial_maintenance" ? "maintenance_request_start" : "repair_request_start"; pushConversionEvent(event, { serviceType: selected, ctaLocation: "service-selector", linkUrl: destination }); window.location.assign(destination); }
  return <section className="mx-auto max-w-3xl px-5 py-16 sm:py-24"><h1 className="text-4xl font-black tracking-tight">{copy.title}</h1><p className="mt-4 text-lg text-black/70">{copy.intro}</p>{coupon ? <div role="status" className="mt-6 rounded-2xl border-2 border-dashed border-brand-red bg-red-50 p-5"><p className="text-sm font-bold uppercase tracking-wide text-brand-red">{locale === "es" ? "Cupón guardado" : "Coupon saved"}</p><p className="mt-1 text-2xl font-black">{coupon}</p><p className="mt-1 font-bold text-black">{locale === "es" ? "Precio regular $174 — Ahorre $25 — Ahora $149" : "Regularly $174 — Save $25 — Now $149"}</p><p className="mt-1 text-sm text-black/70">{locale === "es" ? "Mostraremos este código al continuar. Menciónelo también al equipo de GC." : "We’ll carry this code forward. Mention it to the GC team as well."}</p></div> : null}<fieldset className="mt-8 grid gap-3 sm:grid-cols-2"><legend className="sr-only">{copy.title}</legend>{PUBLIC_SCHEDULE_SERVICES.map((service) => { const label = coupon && service === "maintenance" ? (locale === "es" ? "Afinación HVAC — Precio regular $174 — Ahorre $25 — Ahora $149" : "HVAC Tune-Up — Regularly $174 — Save $25 — Now $149") : SERVICE_LABELS[locale][service]; return <label key={service} className={`cursor-pointer rounded-2xl border-2 p-4 font-semibold transition ${selected === service ? "border-brand-red bg-red-50" : "border-black/10 hover:border-black/30"}`}><input className="mr-3" type="radio" name="service" value={service} checked={selected === service} onChange={() => setSelected(service)} />{label}</label>; })}</fieldset><button type="button" onClick={continueToCustomerFlow} className="mt-8 w-full rounded-xl bg-brand-red px-6 py-4 font-bold text-white">{copy.button}</button><p className="mt-3 text-sm text-black/60">{copy.note}</p></section>;
}
