import assert from "node:assert/strict";
import { pendingProductionFields } from "../lib/commercial-config";
import { validateContact } from "../lib/contact-schema";
import { isServiceType } from "../lib/service-types";
import { LOCALIZED_ROUTES, alternateLocalePath } from "../lib/routes";
import { customerFlowHref, dispatchServiceHref, scheduleServiceHref } from "../lib/scheduling";
import { PROMOTIONS } from "../lib/promotions";
import { SYSTEM_TYPES, validateInstallation } from "../lib/installation-schema";
assert.equal(isServiceType("installation"), true);
assert.equal(isServiceType("free_quote"), false);
assert.equal(SYSTEM_TYPES.includes("window_ac" as never), false);
assert.equal(scheduleServiceHref("ac_repair"), "/schedule-service/?service=ac_repair");
assert.equal(scheduleServiceHref("installation", "es"), "/es/programar-servicio/?service=installation");
assert.notEqual(dispatchServiceHref("ac_repair"), dispatchServiceHref("maintenance"));
assert.match(PROMOTIONS.repairs.ctaPrimary.href, /service=ac_repair/);
assert.equal(PROMOTIONS["new-installation"].ctaPrimary.href, "/residential/residential-ac-installation/#free-hvac-quote");
assert.equal(customerFlowHref("installation"), "/residential/residential-ac-installation/#free-hvac-quote");
assert.match(PROMOTIONS["tune-ups"].ctaPrimary.href, /service=maintenance/);
assert.match(PROMOTIONS["tune-ups"].ctaPrimary.href, /coupon=GC149/);
assert.match(PROMOTIONS["tune-ups"].metaTitle, /Regularly \$174.*Save \$25.*Now \$149/);
const obsoletePrices = ["$" + "99", "$" + "199", "Save $" + "50"];
for (const obsolete of obsoletePrices) assert.equal(JSON.stringify(PROMOTIONS["tune-ups"]).includes(obsolete), false);
const tuneUpDispatch = new URL(dispatchServiceHref("maintenance", "GC149"));
assert.equal(tuneUpDispatch.searchParams.get("coupon"), "GC149");
assert.match(tuneUpDispatch.searchParams.get("service_label") ?? "", /Regularly \$174.*Save \$25.*Now \$149/);
assert.deepEqual(pendingProductionFields(), []);
assert.equal(new Set(Object.values(LOCALIZED_ROUTES).flatMap((route) => [route.en, route.es])).size, Object.keys(LOCALIZED_ROUTES).length * 2);
assert.deepEqual(alternateLocalePath("/"), { en: "/", es: "/es/" });
assert.deepEqual(alternateLocalePath("/es"), { en: "/", es: "/es/" });
assert.deepEqual(alternateLocalePath("/es/"), { en: "/", es: "/es/" });
const valid = validateContact({ name: "Test User", email: "test@example.com", phone: "714 555 1212", service: "ac_repair", zip: "90703", message: "Air conditioner is not cooling.", consent: true, turnstileToken: "test" });
assert.equal(valid.success, true);
const invalid = validateContact({ name: "", email: "not-email", service: "unknown", zip: "1", message: "short", consent: false });
assert.equal(invalid.success, false);
if (!invalid.success) { assert.ok(invalid.errors.email); assert.ok(invalid.errors.zip); assert.ok(invalid.errors.consent); }
const installation = validateInstallation({ firstName: "Test", lastName: "Homeowner", phone: "714 555 1212", email: "test@example.com", zipCode: "90703", homeownerStatus: "homeowner", projectType: "upgrade_existing_system", comfortNeeds: ["high_energy_bills"], systemType: "heat_pump", timeline: "within_30_days", financingInterest: "maybe", consent: true, turnstileToken: "test", attribution: { gclid: "test-click", utm_source: "google" }, ctaSource: "hero" });
assert.equal(installation.success, true);
console.log("Core validation tests passed.");
